### ISSUE TITLE
SVG Edit Shapes doesn't work

### ISSUE THREAD

**Issue by nicolasd** [progers/pathseg#1]
When trying to add a Shape on SVG Edit with the pathseg js, shapes doesn't work.

For example, try to select Smiley shape and add this in the page.

It will blink and the smiley will resize badly
![svgedit](https://cloud.githubusercontent.com/assets/459201/10965262/0e460e86-83ac-11e5-9afc-c85ae738cdbd.png)

**Comment by progers** [comment]
Including the pathseg polyfill in svg-edit isn't 100% straightforward due to the order of dependencies. Are you using the pull request I submitted here?
https://github.com/SVG-Edit/svgedit/pull/20

**Comment by progers** [comment]
I'm sorry, I misunderstood. The shape tool in particular is indeed broken. Investigating..

**Comment by progers** [comment]
Fixed with https://github.com/progers/pathseg/commit/11f7e5a958aac953bc9bd49ac4f0d91e1d108841!

Pathseg.js has some 400 tests, I'm surprised this slipped by. I added a new test in the pathseg repo and updated the svg-edit pull request to use the new code.

Thanks for taking the time to test this and report a bug.

**Comment by nicolasd** [comment]
Hello,
A big thank you, 
i confirm that everything is working now !

thanks
