### ISSUE TITLE
Implement the getPathSegAtLength interface

### ISSUE THREAD

**Issue by progers** [progers/pathseg#17]
There is a discussion about removing getPathSegAtLength from blink:
https://groups.google.com/a/chromium.org/d/msg/blink-dev/Gc1Aw282beo/NsfsKf8LBgAJ

Original spec:
https://www.w3.org/TR/SVG11/paths.html#__svg__SVGPathElement__getPathSegAtLength

This isn't super simple to implement because it requires the distance-along-a-path algorithm.

**Comment by AmeliaBR** [comment]
A naive implementations would be to use the browser's distance-along-a-path algorithm from `getTotalLength()`, creating a new path element and progressively adding copies of each path segment, in order, measuring the total length after that segment was added.  

You would probably want to cache the lengths for each segment, so that the next time the method is called you could just scan through, adding the pre-computed numbers.  However, you'd have to make sure to invalidate the saved length any time the segment is altered, including a change to the end-point of the previous segment.  And for the "smooth" segments and "z" segments, it would get more complicated -- their length can change based on a change in a parameter from a much earlier segment  (E.g., if you have a QTTTTTTT path, the final T is affected by the control point on the Q).

**Comment by progers** [comment]
This was straightforward to implement using your getTotalLength observation. I went with a simple O(n^2) approach without auxiliary caches. Would you be up for reviewing the pull request?

**Comment by progers** [comment]
On my walk to work this morning I realized a subtlety of this algorithm if a later segment could affect the path of previous segments (similar to your QTTTTT example but where changes to later segments affect earlier segments). I don't think this can happen.

For example, a path like "seg0, seg1, seg2, seg3":
length(seg0, seg1) = 5
length(seg1, seg2) = 4
length(seg2, seg3) = 8
And total length = 5+4+8 = 17

The algorithm in this PR pretty much calculates the length of these subpaths:
"seg0 seg1 seg2 seg3" = 5+4+8 = 17
"seg0 seg1 seg2" = 5+4 = 9
"seg0 seg1" = 5
The path segment at distance=10 would be seg3.

This algorithm can only work if removing seg3 has no effect on the lengths of seg0->seg1 and seg1->seg2. For example, if we had the following scenario:
"seg0 seg1 seg2 seg3" = 5+4+8 = 17
"seg0 seg1 seg2" = 5+6 = 11
"seg0 seg1" = 5
Asking for the path seg at distance=10 would incorrectly return seg2 instead of seg3.


I don't have a proof of this but I couldn't find path segment types where later segments change control points of previous segments. So, I think the algorithm in this PR works.

**Comment by AmeliaBR** [comment]
None of the existing path segment types have lengths that are affected by subsequent segments.  The proposed Catmull-Rom spline would be another matter, but I don't think you have to worry about that any time soon.
