### ISSUE TITLE
When accessing path segments through indexer, it doesn't keep references.

### ISSUE THREAD

**Issue by ChrisEelmaa** [progers/pathseg#5]
I am not 100% sure it is bug, however, my code is working fine on chrome#47, and after I switch to #48 with this polyfill, it doesn't work anymore.

The code before:

`
var pathDomSegments = pathDom.pathSegList;
function getPathDomSegmentByGuid(guid) {
    var pathDomSegment = pathDomSegmentMetadata[guid];
    for (var i = pathDomSegments.numberOfItems - 1; i >= 0; i--) {
        if (pathDomSegment === pathDomSegments[i])
            return {
                index: i,
                pathDomSegment: pathDomSegment
            };
    }
}`

Doesn't work anymore because === is not working with pathDomSegments[i], I assume it's reference validity issue,

As a workaround, I had to switch to **getItem** this in order for this to start working:
`
var pathDomSegments = pathDom.pathSegList;
function getPathDomSegmentByGuid(guid) {
    var pathDomSegment = pathDomSegmentMetadata[guid];
    for (var i = pathDomSegments.numberOfItems - 1; i >= 0; i--) {
        if (pathDomSegment === pathDomSegments.getItem(i))
            return {
                index: i,
                pathDomSegment: pathDomSegment
            };
    }
}`

Great work by the way!

**Comment by progers** [comment]
Thank you for taking the time to report this!

I confirmed that this did work before, and the history is interesting.

The array access was only added to SVG2 in early 2014 and was implemented by Chromium/blink and Firefox but not Safari/webkit. Then, SVG2 removed all of SVGPathSegList in 2015, so only browsers that implemented the spec for a short period had this feature.

It turns out to be quite difficult to polyfill operator[]. There is a way with an ES6 thing called proxies, but it's not the most performant. I think it would be best to leave this broken in the polyfill for simplicity and speed, even though it would be more correct to support it.
